language: go
go:
  - 1.13
  - 1.14
before_install:
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
script: go vet -v ./... && golint ./... && $GOPATH/bin/goveralls -service=travis-ci -flags -count=20
